version: '3.9'

services:
  MSSqlServer:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    # Adding container name to make sure connection string doesn't fails
    container_name: "MSSqlServer"
    # Adding port mapping, using 1433 as default
    ports:
     - "1433:1433"
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=My*Secure*Password*1
  miroservicesdemo.order:
    image: ${DOCKER_REGISTRY-}miroservicesdemoorder
    container_name: "OrderApi"
    environment:
     - ASPNETCORE_URLS="http://+:80"
     - ASPNETCORE_ENVIRONMENT=Development
     - ConnectionStrings__OrderSqlDb=Server=MSSqlServer;Database=OrderDb;User Id=SA;Password=My*Secure*Password*1;MultipleActiveResultSets=true
    build:
      context: .
      dockerfile: MiroservicesDemo.Order/Dockerfile
    ports:
     - "8080:80"
    depends_on:
     - MSSqlServer
    command:
    # Linux sleep command. Syntax: sleep number[suffix: s(default),m,h,d]. Example: sleep 0.05m
     - "sleep 10;"